# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'



steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      sudo pip install --upgrade cryptography


- task: CopyFiles@2
  inputs:
    SourceFolder: 'factory-ai-vision/EdgeSolution'
    Contents: |
      deployment.*.template.json
      **/module.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact Drop.'