apiVersion: v1
kind: Secret
metadata:
  name: azure-env
type: Opaque
data:
  IOTHUB_CONNECTION_STRING: {{ required "Azure IoTHub Connection String is required!" .Values.azureIoT.hubConnectionString | b64enc | quote }}
  IOTEDGE_DEVICE_CONNECTION_STRING: {{ required "Azure IoTEdge Device Connection String is required!" .Values.azureIoT.edgeConnectionString | b64enc | quote }}