stages:
  - build
  - scan
  - deploy

.dockerhublogin: &dockerhublogin
  before_script:
    - echo ${dockerhub_access_token} | docker login --username ${dockerhub_username} --password-stdin

build-dev:
  stage: build
  <<: *dockerhublogin 
  image: docker:19.03.12
  services:
      - name: docker:19.03.12-dind
  tags: [proj-1739-runner]
  script:
    - docker build -t $CI_PROJECT_NAME .
    - CID=$(docker create $CI_PROJECT_NAME)
    - docker cp $CID:/usr/src/app/node_modules/ .
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
    policy: push
  except:
    refs:
      - master
      - tags

scan-code:
  stage: scan
  image: openjdk:11
  tags: [proj-1739-runner]
  script:
    - ./.ci/scan-code.sh $CI_PROJECT_NAME $CI_COMMIT_REF_NAME $blackduck_api_key
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    policy: pull

build-prod:
  stage: build
  <<: *dockerhublogin 
  image: docker:19.03-git
  services:
      - name: docker:19.03.12-dind
  tags: [proj-1739-runner]
  script:
    - echo ${azure_docker_registry_password} | docker login --username ${azure_docker_registry_username} --password-stdin  wwtmsft.azurecr.io
    - ./.ci/build-and-push-image.sh data-analysis latest
  only:
    refs:
      - master

deploy-prod:
  stage: deploy
  image: registry-gitlab.asynchrony.com/proj-1739/build-utils/kubectl
  tags: [proj-1739-runner]
  before_script:
    - mkdir -p ~/.kube/
    - cat $kube_config > ~/.kube/config
  script:
    - ./.ci/k8s-deploy.sh
  only:
    refs:
      - master

