# These values under global are intended to be set by the parent chart, but included here in case you want to deploy individually. 
global:
  fhir_service_name:
  docker_registry:
  service_bus_connection_string:

deployment:
  name: subscriber
  group: subscriber
  replicaCount: 1
  pullPolicy: Always
  imagePullSecrets: acr-secret
  container:
    image_name: subscriber
    tag: latest

nameOverride: ""
fullnameOverride: ""

