apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "mnist-onnx"
spec:
  default:
    predictor:
      onnx:
        storageUri: "pvc://samba-share-claim/mymodels/build_models/mnist-onnx"
