deploy:
  stage: deploy
  image: registry-gitlab.asynchrony.com/proj-1739/build-utils/kubectl
  tags: [proj-1739-runner]
  before_script:
    - mkdir -p ~/.kube/
    - cat $kube_config > ~/.kube/config
  script:
    - ./.ci/k8s-deploy.sh
  only:
    refs:
      - main

